### ISSUE TITLE
Mechanism to fetch a `dev` dependency or from any other group?

### ISSUE THREAD

**Issue by njlr** [soniaai/rules_poetry#15]
Is it possible to fetch a `dev` dependency or from any other group?

**Comment by NathanHowell** [comment]
@njlr the distinction between dependency groups is less important for Bazel builds (testonly being the notable exception), so I hadn’t implemented this. I can see it being useful though. is this something you could help fix?

**Comment by njlr** [comment]
The use-case is maintaining a Poetry build and a Bazel build in parallel.
